IP:
  all: '*'                         # '*' stands for all IPs
  all_drone: 'all_drone'           # all drone, not include station
  groundStation0: 192.168.124.10   # laptop (grond station)
  drone1: 192.168.124.101        # drone 1 zld-4
  drone2: 192.168.0.113        # drone 2 zld-5
